version: '3.9'
services:
  backend:
    build:
      context: Backend
    command:
      - gunicorn
      - "Iris.wsgi:application"
      - "-b"
      - "0.0.0.0:8000"
      - "-w"
      - "2"
    depends_on:
      - db
  frontend:
    build:
      context: Frontend
# O el comando específico para iniciar el servidor de desarrollo de SvelteKit
    command: node index.js
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=irisdb
      - POSTGRES_USER=iris
      - POSTGRES_PASSWORD=irispassword
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf